---

layer3ip:
  - { interface: vlan10, ip: 10.1.10.2, mask: 24 }
  - { interface: vlan20, ip: 10.1.20.2, mask: 24 }

vpc:
  dummy:
    domain: 100
    systempri: 2000
    rolepri: 1000
    pkl:
      src: 54.25.255.13
      dest: 54.25.255.14
      vrf: management

hsrp_priority: 120